TELEGRAM_TOKEN = "PUT_YOUR_BOT_TOKEN"
VIP_GROUP_ID = "PUT_GROUP_ID"

PAIRS = [
    "XAU/USDT",
    "US30",
    "NAS100",
    "USD/JPY",
    "GBP/USD",
    "NZD/USD"
]

MAX_TRADES_PER_DAY = 3
RISK_PER_TRADE = 0.01

CONFIDENCE_THRESHOLD = 75
